#### 1. numpy 패키지 불러오기

In [130]:
import numpy as np

#### 2. 리스트로부터 배열 생성

In [131]:
my_list = [1,2,3,4]
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

#### 3. 크기가 10인 zero 벡터 생성(단, 다섯번째 값은 1) 

In [132]:
Z = np.zeros(10)
Z[4] = 1
Z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 4. 0-8까지의 정수로 이루어진 3X3 배열 생성

In [48]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 5. 난수로 이루어진 5x5 배열을 만들고 최댓값, 최솟값 찾기

In [133]:
Z = np.random.random((5,5))
print (Z)
print (Z.min())
print (Z.max())

[[ 0.97117754  0.42853436  0.864607    0.27670701  0.89646286]
 [ 0.28523282  0.656535    0.90718939  0.93921203  0.74773416]
 [ 0.96661107  0.9301396   0.7671255   0.26635383  0.27816492]
 [ 0.48875151  0.77184793  0.6267793   0.90871721  0.25057369]
 [ 0.93588196  0.67410651  0.44109973  0.63224945  0.97292984]]
0.250573690059
0.972929836502


#### 5-1. 각 행별로 최솟값 찾기

In [30]:
Z.min(axis=1)

array([ 0.71236082,  0.29759996,  0.02440725,  0.38502136,  0.05882211])

#### 6. 크기가 10인 random 벡터 오름차순 정렬

In [134]:
Z = np.random.random(10)
print (Z)
Z.sort()
print(Z)

[ 0.5516139   0.84428432  0.64021728  0.49788761  0.44690892  0.29667577
  0.15887132  0.0776808   0.69280222  0.56560731]
[ 0.0776808   0.15887132  0.29667577  0.44690892  0.49788761  0.5516139
  0.56560731  0.64021728  0.69280222  0.84428432]


#### 7.  크기가 10인 random 벡터에서 값이 가장 클 때의 인덱스 찾기

In [39]:
Z = np.random.random(10)
print (Z)
Z.argmax()

[ 0.29387898  0.71943974  0.13222164  0.3415192   0.10763964  0.0352474
  0.30641629  0.48917157  0.37425966  0.14205476]


1

#### 7-1. 최댓값을 0으로 변경

In [40]:
Z[Z.argmax()] = 0
print (Z)

[ 0.29387898  0.          0.13222164  0.3415192   0.10763964  0.0352474
  0.30641629  0.48917157  0.37425966  0.14205476]


#### 8. 행렬에서 각 행별 평균 빼기

In [45]:
X = np.random.rand(3, 4)
Y = X - X.mean(axis=1, keepdims=True)
print (Y)

[[ 0.12410958 -0.18539018  0.44967285 -0.38839225]
 [-0.17799189 -0.23013835  0.12240252  0.28572771]
 [-0.09626169 -0.17268119  0.20934429  0.05959859]]


#### 9. [1,2,0,0,4,0]로부터 값이 0이 아닌 곳의 인덱스 찾기

In [136]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 10. [-1,3,-2,4,5,7,9,10]로부터 음수값은 0으로 변경하기

In [75]:
arr = np.array([-1,3,-2,4,5,7,9,10])
np.where(arr < 0, 0, arr)

array([ 0,  3,  0,  4,  5,  7,  9, 10])

### 10명의 키, 몸무게, 나이, 성별, 혈액형에 대한 데이터가 있다.

#### 1) 10명에 대한 키 배열을 생성하시오.(평균=170, 표준편차=10)

In [137]:
mu, sigma = 170, 10 # mean and standard deviation
height = np.random.normal(mu, sigma, 10)
height

array([ 182.95650085,  157.78714449,  180.78250923,  179.70719986,
        170.78838065,  149.11316896,  174.83330767,  182.41841159,
        172.34709746,  168.91663254])

#### 2) 10명에 대한 몸무게 배열을 생성하시오. (0과 1사이 random number X 100)

In [138]:
weight = np.random.rand(10) * 100
weight

array([ 20.33529746,  72.98033292,  92.9248777 ,  36.36475211,
        90.62050884,  45.4172702 ,  46.331283  ,  37.30471429,
        75.40871258,  89.82582753])

#### 3) 10명에 대한 나이 배열을 생성하시오. [10, 80) 정수

In [139]:
age = np.random.randint(10,80,size=10)
age

array([67, 35, 47, 56, 52, 49, 39, 16, 56, 21])

#### 4) 10명에 대한 성별 배열을 생성하시오. (0 : 남자, 1 : 여자)

In [140]:
sex = np.random.randint(0,2,size=10)
sex

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1])

#### 5) 10명에 대한 혈액형 배열을 생성하시오. (0 : 'A', 1 : 'B', 2 : 'O', 3 : 'AB')

In [141]:
blood = np.random.choice([0,1,2,3], size=10)
blood

array([3, 3, 1, 0, 2, 3, 2, 1, 0, 2])

#### 6) 10행 5행의 배열로 합치시오. 

In [142]:
info_arr = np.column_stack((height, weight, age, sex, blood))
info_arr

array([[ 182.95650085,   20.33529746,   67.        ,    0.        ,    3.        ],
       [ 157.78714449,   72.98033292,   35.        ,    0.        ,    3.        ],
       [ 180.78250923,   92.9248777 ,   47.        ,    1.        ,    1.        ],
       [ 179.70719986,   36.36475211,   56.        ,    1.        ,    0.        ],
       [ 170.78838065,   90.62050884,   52.        ,    1.        ,    2.        ],
       [ 149.11316896,   45.4172702 ,   49.        ,    0.        ,    3.        ],
       [ 174.83330767,   46.331283  ,   39.        ,    0.        ,    2.        ],
       [ 182.41841159,   37.30471429,   16.        ,    1.        ,    1.        ],
       [ 172.34709746,   75.40871258,   56.        ,    1.        ,    0.        ],
       [ 168.91663254,   89.82582753,   21.        ,    1.        ,    2.        ]])

#### 7) 여성의 비율은?

In [143]:
female = info_arr[:,3].sum()
total = len(info_arr[:,3])
print ('ratio of female :', (female/total) * 100)

ratio of female : 60.0


#### 8) 여자이면서 B형인 사람의 수는?

In [144]:
((info_arr[:,3] == 1) & (info_arr[:,4] == 2)).sum()

2

#### 9) 여자들의 키, 몸무게, 나이를 출력하시오.

In [145]:
info_arr[info_arr[:, 3] == 1, :3]

array([[ 180.78250923,   92.9248777 ,   47.        ],
       [ 179.70719986,   36.36475211,   56.        ],
       [ 170.78838065,   90.62050884,   52.        ],
       [ 182.41841159,   37.30471429,   16.        ],
       [ 172.34709746,   75.40871258,   56.        ],
       [ 168.91663254,   89.82582753,   21.        ]])

In [146]:
## 참고 : 만약에 키, 나이, 혈액형만 보고 싶다면?
info_arr[info_arr[:, 3] == 1][:, [0,2,4]] 

array([[ 180.78250923,   47.        ,    1.        ],
       [ 179.70719986,   56.        ,    0.        ],
       [ 170.78838065,   52.        ,    2.        ],
       [ 182.41841159,   16.        ,    1.        ],
       [ 172.34709746,   56.        ,    0.        ],
       [ 168.91663254,   21.        ,    2.        ]])

#### 10) 남자들의 키의 평균은?

In [147]:
info_arr[info_arr[:, 3] == 0, 0].mean()

166.17253049221566

#### 11) 10명에 BMI에 대한 배열을 생성하시오. (BMI = weight[kg]/height[m]^2)

In [148]:
height_m_sqr = (info_arr[:,0] * 0.01) ** 2
weight = info_arr[:,1]
BMI = weight / height_m_sqr

In [149]:
BMI

array([  6.07511969,  29.31315786,  28.43277041,  11.26029263,
        31.06775381,  20.42626809,  15.15744422,  11.21053602,
        25.38712836,  31.48157104])

Underweight: BMI is less than 18.5

Normal weight: BMI is 18.5 to 24.9

Overweight: BMI is 25 to 29.9

Obese: BMI is 30 or more